### PR TITLE
Added avrdude options and backup button

### PR DESCRIPTION
**Pull request by benlye**
- Added configurable options for the AVR MCU and programmer - just two options for each at the moment as that's all the hardware I have to test with
- Added a 'read_firmware' method to read the current firmware and send it back to the browser for download
- Modified the names of a couple of the javascript variables

I've tried this on my 1284p and mega2560 boards and it seems to work OK on both :-)

### CODE REVIEW

**Comment by foosel** [comment]
First of all apologies for the huge delay in taking a look at this 😕 First I was on an overdue vacation, and after I got back from that I caught myself the nastiest flu of the past couple of years that put me out of commission for several weeks. Still working through my backlog from that.

Now, about this PR... There's an issue I see here with the implementation of your backup approach. The thing is, the way that OctoPrint is currently built, we have a single threaded webserver (Tornado), serving a WSGI application (Flask). WSGI is a synchronous interface. And that means that as long as the server is processing one API request, it can't process any others (and yes, that is something I really hate and want to change but sadly it's the way things are at the moment). Case in point, the server will effectively lock up as long as the current hex dump is being read from the micro controller and not be able to process any other requests in the meantime.

To get around this, I'd suggest to instead approach this with a more "backup job" kinda view. Client sends backup request. Backup is started, returns something like 201, and tells the client "ok, I'm on it, here's the URL you'll be able to download the backup from". Client polls the URL (or - better yet - waits until a notification from the server through the socket), once the file is ready the server's response on the URL switches from something like 202 to 200 and the file is sent over. I'd also serve the URL up via a Tornado route instead of a Flask blueprint endpoint - those are better suited for larger files but can be easily added through a plugin hook as well.

I'd immediately merge the avrdude option stuff, but the backup bit needs work I fear to not risk blocking of the server. Suggestion: How about you move the backup into its own PR? Then I could merge this one, make a new release and finally push the plugin to the repo, and we tackle the backup (maybe even with some storage in case one is prone to experiment) with the next version?

**Comment by benlye** [comment]
Hi Gina, no problem on the delay, and thanks for the helpful insight.  I'll update this PR to remove the backup function and then work on doing as you suggest.  Might need a few days as I've become quite busy myself ;-)

**Comment by foosel** [comment]
@benlye got an ETA? :) Not a problem if not. I'm just asking because this is what I'm waiting for to push a new release and get this plugin on the repo, and I don't want to do that now if your adjusted PR is just around the corner :)

**Comment by andrivet** [comment]
I have created another PR (#14) with only avrdude option modifications.

**Comment by drdelaney** [comment]
I can confirm that PR (#14) seems to function correctly with a pi zero and a Sanguinololu 1.3a board.

**Comment by foosel** [comment]
Just to verify: saw #14, will merge ASAP. Got my hands full again sadly. 

Anyone interested in adopting this plugin after all maybe? I fear OctoPrint proper is simply taking up too much time to do this thing justice after all.

**Comment by benlye** [comment]
@andrivet, thanks for picking up where I left off.  I had to replace my Raspberry Pi and then I was struggling with an issue where I couldn't get the upload button to enable - turns out that it doesn't seem to work properly when the serial connection serial port is set to 'Auto' and the firmware update plugin is set to a specific port.  Need to investigate that a bit more.

Anyway - happy to see progress on this :-)

The code in #14 looks like it was adapted from mine in #11 so I'd be happy to volunteer to adopt the plugin.

**Comment by foosel** [comment]
@benlye Awesome! I just added you as a collaborator!

Also funny that you ran into this upload button issue too. I was looking into this plugin again just last week to push out a new release (without this PR or #14 since I just wanted it to finally go out), then ran into this, was completely stumped and then had to take care of other things again.

So - better this is in the hands of someone who doesn't get pulled away by other things all the time I guess ;)

**Comment by andrivet** [comment]
@foosel @benlye  Once #14 has been merged, I can look at this AUTO problem if you want. I also want to add more programmers (I owned an Atmel ICE and and AVR Dragon) and default values.

**Pull request closed without merging**
