### PR TITLE
Add Python 3 support

### PR DESCRIPTION
**Pull request by onovy**

### CODE REVIEW

**Comment by benlye** [comment]
Thanks for this.  I'll get it merged and a new release out ASAP 👍

**Comment by jneilliii** [comment]
FYI...don't forget to update the plugin repository (plugins.octoprint.org) in order for Plugin Manager to be able to find the plugin as well. Additional information can be found [here](https://docs.octoprint.org/en/master/plugins/python3_migration.html#telling-octoprint-your-plugin-is-python-3-ready).

**Comment by onovy** [comment]
which is done in octoprint_firmwareupdater/__init__.py file in this PR

**Comment by jneilliii** [comment]
I'm specifically talking about updating the plugin repository, not this plugin directly, but it's Jekyll template md file on plugins.octoprint.org. if you don't update that then this plugin will not be able to be found in plugin manager when running under python 3 environments.

**Comment by jneilliii** [comment]
This page....

https://github.com/OctoPrint/plugins.octoprint.org/blob/gh-pages/_plugins/firmwareupdater.md

**Comment by onovy** [comment]
ah right, thanks

**Comment by benlye** [comment]
Sorry about the delay - work has been crazy for the past couple of weeks.  I'm testing this now and will update the plugin repo as soon as I'm finished.

**Pull request merged**
